export const ROUTE_NAMES = {
  HOME: 'Home',
  LOGIN: 'Login',
  OAUTH_CALLBACK: 'OAuthCallback',
  BROKER_CONNECT: 'BrokerConnect',
  BROKER_VERIFY: 'BrokerVerify',
  BROKER_LOGIN: 'BrokerLogin',
  BROKER_HOLDINGS: 'BrokerHoldings',
  BROKER_COMPLETE: 'BrokerComplete',
  JOURNAL: 'Journal',
  JOURNAL_CREATE: 'JournalCreate',
  PORTFOLIO: 'Portfolio',
  TENDENCY: 'Tendency',
  TENDENCY_HISTORY_DETAIL: 'TendencyHistoryDetail',
  TENDENCY_RECOMMENDATIONS: 'TendencyRecommendations',
  TENDENCY_PRINCIPLES_EDIT: 'TendencyPrinciplesEdit',
  AI_CONVERSATION: 'AiConversation',
  SIMULATION: 'Simulation',
  MYPAGE: 'Mypage',
  UI_KIT: 'UIKit',
  NOT_FOUND: 'NotFound',
}
