export const ROUTE_NAMES = {
  HOME: 'Home',
  LOGIN: 'Login',
  JOURNAL: 'Journal',
  JOURNAL_SEARCH: 'JournalSearch',
  JOURNAL_CREATE: 'JournalCreate',
  JOURNAL_DATE: 'JournalDate',
  PORTFOLIO: 'Portfolio',
  TENDENCY: 'Tendency',
  AI_CONVERSATION: 'AiConversation',
  SIMULATION: 'Simulation',
  MYPAGE: 'Mypage',
  UI_KIT: 'UIKit',
  NOT_FOUND: 'NotFound',
}
