<script setup>
import {
  Activity,
  ArrowRight,
  ArrowUpRight,
  BarChart3,
  Bell,
  Bot,
  BookOpen,
  BriefcaseBusiness,
  Camera,
  CalendarRange,
  ChartPie,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleCheck,
  CircleHelp,
  Ellipsis,
  Database,
  Flag,
  Headphones,
  History,
  House,
  Image as ImageIcon,
  Landmark,
  Link,
  Link2Off,
  LoaderCircle,
  Lock,
  LockKeyhole,
  LogOut,
  Megaphone,
  Medal,
  MessageCircle,
  Minus,
  Notebook,
  Pause,
  Pencil,
  PawPrint,
  Play,
  Plus,
  Radar,
  RefreshCw,
  Rocket,
  RotateCcw,
  Scale,
  Search,
  Settings,
  ShieldCheck,
  Sparkles,
  Swords,
  Target,
  TrendingUp,
  TriangleAlert,
  Trophy,
  User,
  UserRoundX,
  Users,
  WalletCards,
  X,
} from '@lucide/vue'

const iconComponents = {
  activity: Activity,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'bar-chart': BarChart3,
  bell: Bell,
  bot: Bot,
  'book-open': BookOpen,
  'briefcase-business': BriefcaseBusiness,
  camera: Camera,
  'calendar-range': CalendarRange,
  'chart-pie': ChartPie,
  check: Check,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'circle-check': CircleCheck,
  'circle-help': CircleHelp,
  ellipsis: Ellipsis,
  database: Database,
  flag: Flag,
  headphones: Headphones,
  history: History,
  home: House,
  house: House,
  image: ImageIcon,
  landmark: Landmark,
  link: Link,
  'link-2-off': Link2Off,
  'loader-circle': LoaderCircle,
  lock: Lock,
  'lock-keyhole': LockKeyhole,
  'log-out': LogOut,
  megaphone: Megaphone,
  medal: Medal,
  'message-circle': MessageCircle,
  minus: Minus,
  notebook: Notebook,
  pause: Pause,
  pencil: Pencil,
  'paw-print': PawPrint,
  play: Play,
  plus: Plus,
  radar: Radar,
  'refresh-cw': RefreshCw,
  rocket: Rocket,
  'rotate-ccw': RotateCcw,
  scale: Scale,
  search: Search,
  settings: Settings,
  'shield-check': ShieldCheck,
  sparkles: Sparkles,
  swords: Swords,
  target: Target,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  trophy: Trophy,
  user: User,
  'user-round-x': UserRoundX,
  users: Users,
  'wallet-cards': WalletCards,
  x: X,
}

defineProps({
  name: {
    type: String,
    required: true,
  },
  size: {
    type: [Number, String],
    default: 20,
  },
})
</script>

<template>
  <component
    :is="iconComponents[name]"
    class="app-icon"
    :size="size"
    :stroke-width="1.8"
    aria-hidden="true"
  />
</template>

<style scoped>
.app-icon {
  display: block;
  flex: 0 0 auto;
}
</style>
